# tester container image
TESTER_IMAGE?=rmt-client-tester

# docker container actions
.PHONY: docker-build docker-start docker-run docker-ps docker-status docker-logs docker-stop

# build the tester image
docker-build: vet
	$(CNTR_MGR) build \
		--pull \
		--tag $(TESTER_IMAGE) \
		--target $(TESTER_IMAGE) \
		.

docker-clean:
	$(CNTR_MGR) buildx prune -f --filter="until=24h" && \
	$(CNTR_MGR) image prune -f

clean:: docker-clean
