package client

import (
	"github.com/rtamalin/rmt-client-testing/internal/choice"
)

var metalPciDataHeader = []string{
	"00:00.0 Host bridge: Intel Corporation Sky Lake-E DMI3 Registers (rev 07)",
	"00:04.0 System peripheral: Intel Corporation Sky Lake-E CBDMA Registers (rev 07)",
	"00:05.0 System peripheral: Intel Corporation Sky Lake-E MM/Vt-d Configuration Registers (rev 07)",
	"00:08.0 System peripheral: Intel Corporation Sky Lake-E Ubox Registers (rev 07)",
	"00:11.0 Unassigned class [ff00]: Intel Corporation C620 Series Chipset Family MROM 0 (rev 09)",
	"00:14.0 USB controller: Intel Corporation C620 Series Chipset Family USB 3.0 xHCI Controller (rev 09)",
	"00:16.0 Communication controller: Intel Corporation C620 Series Chipset Family MEI Controller #1 (rev 09)",
	"00:17.0 SATA controller: Intel Corporation C620 Series Chipset Family SATA Controller [AHCI mode] (rev 09)",
	"00:1f.0 ISA bridge: Intel Corporation C621 Series Chipset LPC/eSPI Controller (rev 09)",
	"17:00.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port A (rev 07)",
	"17:02.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port C (rev 07)",
	"17:05.0 System peripheral: Intel Corporation Sky Lake-E VT-d (rev 07)",
	"17:08.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:09.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:0a.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:0b.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:0e.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:0f.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:10.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:11.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:1d.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"17:1e.0 System peripheral: Intel Corporation Sky Lake-E PCU Registers (rev 07)",
	"34:00.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port A (rev 07)",
	"34:02.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port C (rev 07)",
	"34:05.0 System peripheral: Intel Corporation Sky Lake-E VT-d (rev 07)",
	"34:08.0 System peripheral: Intel Corporation Sky Lake-E Integrated Memory Controller (rev 07)",
	"34:09.0 System peripheral: Intel Corporation Sky Lake-E Integrated Memory Controller (rev 07)",
	"34:0a.0 System peripheral: Intel Corporation Sky Lake-E Integrated Memory Controller (rev 07)",
	"34:0b.0 System peripheral: Intel Corporation Sky Lake-E DECS Channel 2 (rev 07)",
	"34:0c.0 System peripheral: Intel Corporation Sky Lake-E Integrated Memory Controller (rev 07)",
	"34:0d.0 System peripheral: Intel Corporation Sky Lake-E DECS Channel 2 (rev 07)",
	"7a:00.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port A (rev 07)",
	"7a:01.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port B (rev 07)",
	"7a:02.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port C (rev 07)",
	"7a:05.0 System peripheral: Intel Corporation Sky Lake-E VT-d (rev 07)",
	"7a:0e.0 Performance counters: Intel Corporation Sky Lake-E KTI 0 (rev 07)",
	"7a:0f.0 Performance counters: Intel Corporation Sky Lake-E KTI 0 (rev 07)",
	"7a:10.0 Performance counters: Intel Corporation Sky Lake-E KTI 0 (rev 07)",
	"7a:12.0 Performance counters: Intel Corporation Sky Lake-E M3KTI Registers (rev 07)",
	"7a:15.0 System peripheral: Intel Corporation Sky Lake-E M2PCI Registers (rev 07)",
	"7a:16.0 System peripheral: Intel Corporation Sky Lake-E M2PCI Registers (rev 07)",
	"7a:17.0 System peripheral: Intel Corporation Sky Lake-E M2PCI Registers (rev 07)",
	"7b:00.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:00.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:01.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:02.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:03.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:04.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:05.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:06.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:07.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:08.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:09.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:0a.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:0b.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:0c.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:0d.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:0e.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:0f.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:10.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:11.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:12.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:13.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:14.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:15.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:16.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:17.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:18.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:19.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:1a.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:1b.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:1c.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:1d.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:1e.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"7c:1f.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9d:00.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:00.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:01.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:02.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:03.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:04.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:05.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:06.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:07.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:08.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:09.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:0a.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:0b.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:0c.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:0d.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:0e.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:0f.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:10.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:11.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:12.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:13.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:14.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:15.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:16.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:17.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:18.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:19.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:1a.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:1b.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:1c.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:1d.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:1e.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9e:1f.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"9f:00.0 Serial controller: Amazon.com, Inc. Device 8250",
	"c0:04.0 System peripheral: Intel Corporation Sky Lake-E CBDMA Registers (rev 07)",
	"c0:05.0 System peripheral: Intel Corporation Sky Lake-E MM/Vt-d Configuration Registers (rev 07)",
	"c0:08.0 System peripheral: Intel Corporation Sky Lake-E Ubox Registers (rev 07)",
	"c2:00.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port A (rev 07)",
	"c2:05.0 System peripheral: Intel Corporation Sky Lake-E VT-d (rev 07)",
	"c2:08.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:09.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:0a.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:0b.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:0e.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:0f.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:10.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:11.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:1d.0 System peripheral: Intel Corporation Sky Lake-E CHA Registers (rev 07)",
	"c2:1e.0 System peripheral: Intel Corporation Sky Lake-E PCU Registers (rev 07)",
	"c3:00.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:00.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:01.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:02.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:03.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:04.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:05.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:06.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:07.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:08.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:09.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:0a.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:0b.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:0c.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:0d.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:0e.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"c4:0f.0 PCI bridge: Amazon.com, Inc. Device bec2",
	"e6:00.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port A (rev 07)",
	"e6:02.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port C (rev 07)",
	"e6:05.0 System peripheral: Intel Corporation Sky Lake-E VT-d (rev 07)",
	"e6:08.0 System peripheral: Intel Corporation Sky Lake-E Integrated Memory Controller (rev 07)",
	"e6:09.0 System peripheral: Intel Corporation Sky Lake-E Integrated Memory Controller (rev 07)",
	"e6:0a.0 System peripheral: Intel Corporation Sky Lake-E Integrated Memory Controller (rev 07)",
	"e6:0b.0 System peripheral: Intel Corporation Sky Lake-E DECS Channel 2 (rev 07)",
	"e6:0c.0 System peripheral: Intel Corporation Sky Lake-E Integrated Memory Controller (rev 07)",
	"e6:0d.0 System peripheral: Intel Corporation Sky Lake-E DECS Channel 2 (rev 07)",
	"f3:00.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port A (rev 07)",
	"f3:02.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port C (rev 07)",
	"f3:05.0 System peripheral: Intel Corporation Sky Lake-E VT-d (rev 07)",
	"f3:0e.0 Performance counters: Intel Corporation Sky Lake-E KTI 0 (rev 07)",
	"f3:0f.0 Performance counters: Intel Corporation Sky Lake-E KTI 0 (rev 07)",
	"f3:10.0 Performance counters: Intel Corporation Sky Lake-E KTI 0 (rev 07)",
	"f3:12.0 Performance counters: Intel Corporation Sky Lake-E M3KTI Registers (rev 07)",
	"f3:15.0 System peripheral: Intel Corporation Sky Lake-E M2PCI Registers (rev 07)",
	"f3:16.0 System peripheral: Intel Corporation Sky Lake-E M2PCI Registers (rev 07)",
	"f3:17.0 System peripheral: Intel Corporation Sky Lake-E M2PCI Registers (rev 07)",
}

const (
	metalPciBus  = 0xf4
	metalPciSlot = 0
)

var metalModData = []string{
	"aesni_intel",
	"af_packet",
	"ahci",
	"blake2b_generic",
	"btrfs",
	"button",
	"configfs",
	"coretemp",
	"crc32c_intel",
	"crc32_pclmul",
	"crc64",
	"crc64_rocksoft",
	"crc64_rocksoft_generic",
	"cryptd",
	"crypto_simd",
	"dca",
	"dmi_sysfs",
	"dm_log",
	"dm_mirror",
	"dm_mod",
	"dm_region_hash",
	"ena",
	"fat",
	"fuse",
	"ghash_clmulni_intel",
	"i2c_i801",
	"i2c_mux",
	"i2c_smbus",
	"intel_pch_thermal",
	"intel_pmc_bxt",
	"intel_powerclamp",
	"intel_rapl_common",
	"intel_rapl_msr",
	"intel_uncore_frequency",
	"intel_uncore_frequency_common",
	"ioatdma",
	"ipmi_devintf",
	"ipmi_msghandler",
	"ipmi_si",
	"ip_tables",
	"irqbypass",
	"iscsi_boot_sysfs",
	"iscsi_ibft",
	"iTCO_vendor_support",
	"iTCO_wdt",
	"kvm",
	"kvm_intel",
	"libahci",
	"libata",
	"libcrc32c",
	"libnvdimm",
	"lpc_ich",
	"mei",
	"mei_me",
	"mfd_core",
	"nfit",
	"nls_cp437",
	"nls_iso8859_1",
	"nvme",
	"nvme_auth",
	"nvme_core",
	"nvme_keyring",
	"pcspkr",
	"raid6_pq",
	"rfkill",
	"scsi_mod",
	"sd_mod",
	"sg",
	"sha1_ssse3",
	"sha256_ssse3",
	"sha512_ssse3",
	"skx_edac",
	"sunrpc",
	"t10_pi",
	"usbcore",
	"vfat",
	"wmi",
	"x86_pkg_temp_thermal",
	"xfs",
	"xhci_hcd",
	"xhci_pci",
	"xhci_pci_renesas",
	"xor",
	"x_tables",
}

// weighted choice of number of disks for a metal client
var metalDiskChoices = []choice.Choice{
	{
		Weight: 20,
		Value:  1,
	},
	{
		Weight: 25,
		Value:  2,
	},
	{
		Weight: 20,
		Value:  3,
	},
	{
		Weight: 20,
		Value:  4,
	},
	{
		Weight: 10,
		Value:  5,
	},
	{
		Weight: 5,
		Value:  6,
	},
}

// weighted choice of number of GPUs for a metal client
var metalGPUChoices = []choice.Choice{
	{
		Weight: 5,
		Value:  32,
	},
	{
		Weight: 5,
		Value:  24,
	},
	{
		Weight: 20,
		Value:  16,
	},
	{
		Weight: 20,
		Value:  8,
	},
	{
		Weight: 20,
		Value:  4,
	},
	{
		Weight: 10,
		Value:  3,
	},
	{
		Weight: 10,
		Value:  2,
	},
	{
		Weight: 10,
		Value:  1,
	},
}

func MetalClient(id ClientId) *Client {
	c := new(Client)

	numDisk := choice.Choose(metalDiskChoices).(int)
	numGPU := choice.Choose(metalGPUChoices).(int)
	numNet := 1

	c.Init(CLIENT_METAL, id, numDisk, numGPU, numNet)

	c.setupPciData(metalPciDataHeader, metalPciBus, metalPciSlot)
	c.setupModData(metalModData)

	return c
}
